### ISSUE TITLE
this vs. activitypub-rails

### ISSUE THREAD

**Issue by m4sk1n** [monorkin/federation_kit#1]
I'm curious, how is it going to differ from [activitypub-rails](https://gitlab.com/prismosuite/activitypub-rails)?

**Comment by m4sk1n** [comment]
I’m looking for new ActivityPub-related projects every day just because I’m curious about them, so I just wanted to get some info about this gem :)

**Comment by monorkin** [comment]
To add a TL;DR activitypub-rails is a Rails specific, one-stop-shop, opinionated solution, this will be general purpose, configurable and less opinionated.
